-- MySQL Script generated by MySQL Workbench
-- Mon Nov 11 19:56:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`department` (
  `department_id` INT NOT NULL,
  `department_name` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`department_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instructor` (
  `instructor_id` INT NOT NULL,
  `instructor_name` VARCHAR(45) NOT NULL,
  `department_id` INT NOT NULL,
  PRIMARY KEY (`instructor_id`),
  INDEX `fk_instructor_department_idx` (`department_id` ASC) ,
  CONSTRAINT `fk_instructor_department`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`courses` (
  `course_id` INT NOT NULL,
  `course_name` VARCHAR(45) NOT NULL,
  `department_id` INT NOT NULL,
  `instructor_id` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_courses_department1_idx` (`department_id` ASC) ,
  INDEX `fk_courses_instructor_idx` (`instructor_id` ASC) ,
  CONSTRAINT `fk_courses_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_instructor`
    FOREIGN KEY (`instructor_id`)
    REFERENCES `mydb`.`instructor` (`instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `mydb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student` (
  `student_id` INT NOT NULL,
  `student_name` VARCHAR(45) NOT NULL,
  `student_age` INT NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`student_has_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`student_has_courses` (
  `student_student_id` INT NOT NULL,
  `courses_course_id` INT NOT NULL,
  PRIMARY KEY (`student_student_id`, `courses_course_id`),
  INDEX `fk_student_has_courses_courses1_idx` (`courses_course_id` ASC) ,
  INDEX `fk_student_has_courses_student1_idx` (`student_student_id` ASC) ,
  CONSTRAINT `fk_student_has_courses_student1`
    FOREIGN KEY (`student_student_id`)
    REFERENCES `mydb`.`student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_courses_courses1`
    FOREIGN KEY (`courses_course_id`)
    REFERENCES `mydb`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departmenthead`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departmenthead` (
  `department_head_id` INT NOT NULL,
  `department_id` INT NOT NULL,
  INDEX `fk_departmenthead_department1_idx` (`department_id` ASC) ,
  INDEX `fk_departmenthead_instructor1_idx` (`department_head_id` ASC) ,
  CONSTRAINT `fk_departmenthead_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `mydb`.`department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departmenthead_instructor1`
    FOREIGN KEY (`department_head_id`)
    REFERENCES `mydb`.`instructor` (`instructor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
